"""
Examples:

- plugin_signature: "A_SIMPLE_PLUGIN"
- pipeline_input_type: "ExampleDatastream"




"""
from time import time
from uuid import uuid4

class DEEPLOY_KEYS:
  STATUS = "status"
  ERROR = "error"
  TRACE = "trace"
  REQUEST = "request"
  RETURN_REQUEST = "return_request"
  STATUS_DETAILS = "status_details"
  APPS = "apps"
  APP_ID = "app_id"
  NONCE = "nonce"
  APP_ALIAS = "app_alias"
  PLUGIN_SIGNATURE = "plugin_signature"
  TARGET_NODES = "target_nodes"
  CURRENT_TARGET_NODES = "current_target_nodes"
  SPARE_NODES = "spare_nodes"
  ALLOW_REPLICATION_IN_THE_WILD = "allow_replication_in_the_wild" # if target nodes are not available
  NR_TARGET_NODES = "nr_target_nodes" # if target nodes are not available
  TARGETS = "targets"
  TARGET_NODES_COUNT = "target_nodes_count"
  AUTH = "auth"
  JOB_ID = "job_id"
  PROJECT_ID = "project_id" # this is the SHA256(UUID) generated by UI
  PROJECT_NAME = "project_name"
  JOB_TAGS = "job_tags"
  JOB_APP_TYPE = "job_app_type"
  CHAINSTORE_RESPONSE = "chainstore_response"
  CHAINSTORE_RESPONSE_KEYS = "chainstore_response_keys"
  PIPELINE_INPUT_TYPE = "pipeline_input_type"
  PIPELINE_INPUT_URI = "pipeline_input_uri"
  PIPELINE_PARAMS = "pipeline_params"
  PIPELINE = "pipeline"
  PIPELINE_CID = "pipeline_cid"
  JOB_CONFIG = "job_config"
  # App params keys
  APP_PARAMS = "app_params"
  APP_PARAMS_IMAGE = "IMAGE"
  APP_PARAMS_CR = "CR"
  # Multi-plugin keys
  PLUGINS = "plugins"
  PLUGIN_INSTANCES = "instances"
  PLUGIN_INSTANCE_ID = "instance_id"
  # Auth result keys
  SENDER = "sender"
  SENDER_ESCROW = "sender_escrow"
  ESCROW_OWNER = "escrow_owner"

  # Config keys
  DATE_UPDATED = "date_updated"
  DATE_CREATED = "date_created"
  

class DEEPLOY_STATUS:
  SUCCESS = "success"
  FAIL = "fail"
  ERROR = "error"
  PENDING = "pending"
  TIMEOUT = "timeout"
  COMMAND_DELIVERED = "command_delivered"

class DEEPLOY_ERRORS:
  GENERIC = "ERR01_DEEPLOY_GENERIC_ERROR"
  NODES1 = "ERR02_DEEPLOY_NODES1"
  NODES2 = "ERR03_DEEPLOY_NODES2"
  NODES3 = "ERR04_DEEPLOY_NODES3"
  NODES4 = "ERR05_DEEPLOY_NODES4"
  NODES5 = "ERR09_DEEPLOY_NODES5"
  NODES6 = "ERR018_DEEPLOY_NODES6"
  NODERES1 = "ERR06_DEEPLOY_TARGET_NODE_RESOURCES1"
  PLINST1 = "ERR07_DEEPLOY_PLUGIN_INSTANCE1"
  APP1 = "ERR08_DEEPLOY_APP1"
  PAYMENT1 = "ERR08_DEEPLOY_PAYMENT1"
  REQUEST1 = "ERR09_REQUEST1"
  REQUEST2 = "ERR10_REQUEST2"
  REQUEST3 = "ERR11_REQUEST3"
  REQUEST4 = "ERR12_REQUEST4"
  REQUEST5 = "ERR13_REQUEST5"
  REQUEST6 = "ERR14_REQUEST6"
  REQUEST7 = "ERR15_REQUEST7"
  REQUEST8 = "ERR16_REQUEST8"
  REQUEST9 = "ERR17_REQUEST9"
  REQUEST10 = "ERR18_REQUEST10"
  REQUEST11 = "ERR22_REQUEST11"
  REQUEST12 = "ERR23_REQUEST12"
  REQUEST13 = "ERR24_REQUEST13"
  NODETAGS1 = "ERR19_NODETAGS1"
  NODETAGS2 = "ERR20_NODETAGS2"
  NODETAGS3 = "ERR21_NODETAGS3"
  JOB_RESOURCES1 = "ERR22_JOB_RESOURCES1"
  JOB_RESOURCES2 = "ERR23_JOB_RESOURCES2"
  JOB_RESOURCES3 = "ERR24_JOB_RESOURCES3"
  PLUGINS1 = "ERR25_DEEPLOY_PLUGINS1"  # Invalid plugins array structure
  PLUGINS2 = "ERR26_DEEPLOY_PLUGINS2"  # Plugin missing required field
  PLUGINS3 = "ERR27_DEEPLOY_PLUGINS3"  # Instance validation failed

class DEEPLOY_RESOURCES:
  # Result dictionary keys
  STATUS = 'status'
  DETAILS = 'details'
  AVAILABLE = 'available'
  REQUIRED = 'required'
  
  # Resource types
  CPU = 'cpu'
  MEMORY = 'memory'
  STORAGE = 'storage'
  
  # Units
  CORES = 'cores'
  MB = 'MB'

  # Resource requirements for the target nodes
  NODE_RESOURCES_REQUEST = 'node_res_req'
  # Resource keys in app_params
  CONTAINER_RESOURCES = 'CONTAINER_RESOURCES'

  # Default values
  DEFAULT_MEMORY = '512m'
  DEFAULT_CPU = 1

  # Resource detail dictionary keys
  RESOURCE = 'resource'
  AVAILABLE_VALUE = 'available'
  REQUIRED_VALUE = 'required'
  UNIT = 'unit'

class DEFAULT_NODE_RESOURCES:
  CPU = 4
  MEMORY = '16GB'

class DEFAULT_CONTAINER_RESOURCES:
  CPU = 1
  MEMORY = '512m'

JOB_TYPE_RESOURCE_SPECS = {
  # Generic Apps
  53: {DEEPLOY_RESOURCES.CPU: 0.25, DEEPLOY_RESOURCES.MEMORY: '512m', DEEPLOY_RESOURCES.STORAGE: '2g'}, # micro
  54: {DEEPLOY_RESOURCES.CPU: 0.5, DEEPLOY_RESOURCES.MEMORY: '1g', DEEPLOY_RESOURCES.STORAGE: '4g'}, # lite
  1: {DEEPLOY_RESOURCES.CPU: 1, DEEPLOY_RESOURCES.MEMORY: '2g', DEEPLOY_RESOURCES.STORAGE: '8g'}, # entry
  2: {DEEPLOY_RESOURCES.CPU: 2, DEEPLOY_RESOURCES.MEMORY: '4g', DEEPLOY_RESOURCES.STORAGE: '16g'}, # low1
  3: {DEEPLOY_RESOURCES.CPU: 2, DEEPLOY_RESOURCES.MEMORY: '8g', DEEPLOY_RESOURCES.STORAGE: '32g'}, # low2
  4: {DEEPLOY_RESOURCES.CPU: 3, DEEPLOY_RESOURCES.MEMORY: '12g', DEEPLOY_RESOURCES.STORAGE: '48g'}, # med1
  5: {DEEPLOY_RESOURCES.CPU: 6, DEEPLOY_RESOURCES.MEMORY: '14g', DEEPLOY_RESOURCES.STORAGE: '56g'}, # med2
  6: {DEEPLOY_RESOURCES.CPU: 8, DEEPLOY_RESOURCES.MEMORY: '22g', DEEPLOY_RESOURCES.STORAGE: '88g'}, # high1
  7: {DEEPLOY_RESOURCES.CPU: 12, DEEPLOY_RESOURCES.MEMORY: '30g', DEEPLOY_RESOURCES.STORAGE: '120g'}, # high2
  8: {DEEPLOY_RESOURCES.CPU: 16, DEEPLOY_RESOURCES.MEMORY: '62g', DEEPLOY_RESOURCES.STORAGE: '248g'}, # ultra1
  9: {DEEPLOY_RESOURCES.CPU: 22, DEEPLOY_RESOURCES.MEMORY: '124g', DEEPLOY_RESOURCES.STORAGE: '496g'}, # ultra2
  # Native Apps
  16: {DEEPLOY_RESOURCES.CPU: 3, DEEPLOY_RESOURCES.MEMORY: '14g'}, # n_entry
  17: {DEEPLOY_RESOURCES.CPU: 8, DEEPLOY_RESOURCES.MEMORY: '22g'}, # n_med1
  18: {DEEPLOY_RESOURCES.CPU: 12, DEEPLOY_RESOURCES.MEMORY: '30g'}, # n_med2
  19: {DEEPLOY_RESOURCES.CPU: 16, DEEPLOY_RESOURCES.MEMORY: '60g'}, # n_high
  20: {DEEPLOY_RESOURCES.CPU: 22, DEEPLOY_RESOURCES.MEMORY: '124g'}, # n_ultra
  # GPU Extra
  21: {DEEPLOY_RESOURCES.CPU: 3, DEEPLOY_RESOURCES.MEMORY: '12g', DEEPLOY_RESOURCES.STORAGE: '48g'}, # g_entry + med1
  22: {DEEPLOY_RESOURCES.CPU: 6, DEEPLOY_RESOURCES.MEMORY: '14g', DEEPLOY_RESOURCES.STORAGE: '56g'}, # g_entry + med2
  23: {DEEPLOY_RESOURCES.CPU: 3, DEEPLOY_RESOURCES.MEMORY: '14g'}, # g_entry + n_entry
  24: {DEEPLOY_RESOURCES.CPU: 8, DEEPLOY_RESOURCES.MEMORY: '22g'}, # g_entry + n_med1
  25: {DEEPLOY_RESOURCES.CPU: 6, DEEPLOY_RESOURCES.MEMORY: '14g', DEEPLOY_RESOURCES.STORAGE: '56g'}, # g_med + med2
  26: {DEEPLOY_RESOURCES.CPU: 8, DEEPLOY_RESOURCES.MEMORY: '22g', DEEPLOY_RESOURCES.STORAGE: '88g'}, # g_med + high1
  27: {DEEPLOY_RESOURCES.CPU: 12, DEEPLOY_RESOURCES.MEMORY: '30g', DEEPLOY_RESOURCES.STORAGE: '120g'}, # g_med + high2
  28: {DEEPLOY_RESOURCES.CPU: 16, DEEPLOY_RESOURCES.MEMORY: '62g', DEEPLOY_RESOURCES.STORAGE: '248g'}, # g_med + ultra1
  29: {DEEPLOY_RESOURCES.CPU: 8, DEEPLOY_RESOURCES.MEMORY: '22g'}, # g_med + n_med1
  30: {DEEPLOY_RESOURCES.CPU: 12, DEEPLOY_RESOURCES.MEMORY: '30g'}, # g_med + n_med2
  31: {DEEPLOY_RESOURCES.CPU: 16, DEEPLOY_RESOURCES.MEMORY: '60g'}, # g_med + n_high
  32: {DEEPLOY_RESOURCES.CPU: 12, DEEPLOY_RESOURCES.MEMORY: '30g', DEEPLOY_RESOURCES.STORAGE: '120g'}, # g_high + high2
  33: {DEEPLOY_RESOURCES.CPU: 16, DEEPLOY_RESOURCES.MEMORY: '62g', DEEPLOY_RESOURCES.STORAGE: '248g'}, # g_high + ultra1
  34: {DEEPLOY_RESOURCES.CPU: 22, DEEPLOY_RESOURCES.MEMORY: '124g', DEEPLOY_RESOURCES.STORAGE: '496g'}, # g_high + ultra2
  35: {DEEPLOY_RESOURCES.CPU: 12, DEEPLOY_RESOURCES.MEMORY: '30g'}, # g_high + n_med2
  36: {DEEPLOY_RESOURCES.CPU: 16, DEEPLOY_RESOURCES.MEMORY: '60g'}, # g_high + n_high
  37: {DEEPLOY_RESOURCES.CPU: 22, DEEPLOY_RESOURCES.MEMORY: '124g'}, # g_high + n_ultra
  38: {DEEPLOY_RESOURCES.CPU: 16, DEEPLOY_RESOURCES.MEMORY: '62g', DEEPLOY_RESOURCES.STORAGE: '248g'}, # g_ultra + ultra1
  39: {DEEPLOY_RESOURCES.CPU: 22, DEEPLOY_RESOURCES.MEMORY: '124g', DEEPLOY_RESOURCES.STORAGE: '496g'}, # g_ultra + ultra2
  40: {DEEPLOY_RESOURCES.CPU: 22, DEEPLOY_RESOURCES.MEMORY: '124g'}, # g_ultra + n_ultra
  # Services
  50: {DEEPLOY_RESOURCES.CPU: 1, DEEPLOY_RESOURCES.MEMORY: '2g', DEEPLOY_RESOURCES.STORAGE: '8g'}, # entry
  51: {DEEPLOY_RESOURCES.CPU: 2, DEEPLOY_RESOURCES.MEMORY: '4g', DEEPLOY_RESOURCES.STORAGE: '16g'}, # low1
  52: {DEEPLOY_RESOURCES.CPU: 3, DEEPLOY_RESOURCES.MEMORY: '12g', DEEPLOY_RESOURCES.STORAGE: '48g'}, # high1
}

class DEEPLOY_PLUGIN_DATA:
  PLUGIN_SIGNATURE = "plugin_signature"
  PLUGIN_INSTANCE = "plugin_instance"
  INSTANCE_ID = "instance_id"
  APP_ID = "app_id"
  NODE = "NODE"
  CHAINSTORE_RESPONSE_KEY = "CHAINSTORE_RESPONSE_KEY"

CONTAINER_APP_RUNNER_SIGNATURE = 'CONTAINER_APP_RUNNER'
WORKER_APP_RUNNER_SIGNATURE = 'WORKER_APP_RUNNER'
CONTAINERIZED_APPS_SIGNATURES = [CONTAINER_APP_RUNNER_SIGNATURE, WORKER_APP_RUNNER_SIGNATURE]

class JOB_APP_TYPES:
  GENERIC = "generic"
  NATIVE = "native"
  SERVICE = "service"


JOB_APP_TYPES_ALL = (
  JOB_APP_TYPES.GENERIC,
  JOB_APP_TYPES.NATIVE,
  JOB_APP_TYPES.SERVICE,
)
DEEPLOY_FORBIDDEN_SIGNATURES = ['ADMIN_CONTAINER_APP_RUNNER']

DEEPLOY_CREATE_REQUEST = {
  "app_alias" : "some_app_name", 
  "project_id" : "DELIVERD_BY_UI = SHA256(UUID)",
  "project_name": "human-readable-project-name",
  "job_id" : "DELIVERED_BY_UI_FROM_SC",
  "job_app_type": "generic",
  "plugin_signature" : "SOME_PLUGIN_01",
  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
  "target_nodes" : [
    "0xai_node_1",
    "0xai_node_2",
  ],
  "spare_nodes" : [
    "0xai_node_1",
    "0xai_node_2",
  ],
  "target_nodes_count" : 0,
  "allow_replication_in_the_wild": False,
  "job_tags": ["REG:EU", "CT:*"],
  "node_res_req" : { # this is the resource requirements for the target nodes
    # this is the resource requirements for the target nodes
    # and is usable for the case when we want to deploy our service on a much 
    # powerful node than the actual container app needs
    # TODO: to be added in UI
      "cpu" : 4,
      "memory" : "16GiB"   
  },
  "app_params" : {
    "IMAGE" : "repo/image:tag",
    "CR_DATA" : {
      "SERVER" : "docker.io",
      "USERNAME" : "user",
      "PASSWORD" : "password",
    },
    "CONTAINER_RESOURCES" : { # this are the resources that will be constrained for the container
      "cpu" : 1,
      "memory" : "512m",
      "ports": {
        "31250": 1849,
        "31251": 80
      }      
    },
    "PORT" : None,
    "NGROK_AUTH_TOKEN" : None,  # put your ngrok API key here
    "NGROK_EDGE_LABEL" : None,  # if we have a already created ngrok edge, we can use it here
    "NGROK_ENABLED" : False, # this tells that the destination plugin instance will USE ngrok
    # TODO: (and observations)
    # - if NGROK_EDGE_LABEL is not None and NGROK_ENABLED is True => normal use
    # - if NGROK_EDGE_LABEL is None and NGROK_ENABLED is True => create/use dynamic url
    # - if NGROK_EDGE_LABEL is not None and NGROK_ENABLED is False => consider NGROK_ENABLED=True
    
    "NGROK_USE_API": True,  # use API or shell for ngrok tunnel creation
    "ENV" : {
      "ENV1" : "value1",
      "ENV2" : "value2",
      "ENV3" : "value3",
      "ENV4" : "value4",
    },
    "DYNAMIC_ENV" : {
      "ENV5" : [
        {
          "type" : "static",
          "value" : "http://"
        },
        {
          "type" : "host_ip",
          "value" : None
        },
        {
          "type" : "static",
          "value" : ":5080/test_api_endpoint"
        }
      ],
      "ENV6" : [
        {
          "type" : "host_ip",
          "value" : "http://"
        }
      ],
    },
    "RESTART_POLICY" : "always",
    "IMAGE_PULL_POLICY" : "always",
    
    
    "OTHER_PARAM1" : "value1",
    "OTHER_PARAM2" : "value2",
    "OTHER_PARAM3" : "value3",
    "OTHER_PARAM4" : "value4",
    "OTHER_PARAM5" : "value5",
  },
  "pipeline_input_type"  : "void",
  "pipeline_input_uri" : None,
  "chainstore_response" : False,
}

###################################################################################################################

DEEPLOY_CREATE_REQUEST_CONTAINER_APP = {
  "app_alias" : "some_app_name", 
  "project_id" : "DELIVERD_BY_UI = SHA256(UUID)",
  "project_name": "human-readable-project-name",
  "job_id" : "DELIVERED_BY_UI_FROM_SC",
  "plugin_signature" : "CONTAINER_APP_RUNNER",
  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
  "target_nodes" : [
    "0xai_node_1",
    "0xai_node_2",
  ],
  "target_nodes_count" : 0,
  "node_res_req" : { # this is the resource requirements for the target nodes
    # this is the resource requirements for the target nodes
    # and is usable for the case when we want to deploy our service on a much 
    # powerful node than the actual container app needs
    # TODO: to be added in UI
      "cpu" : 4,
      "memory" : "16GiB"   
  },
  "app_params" : {
    "IMAGE" : "repo/image:tag",
    "CR_DATA" : {
      "SERVER" : "docker.io",
      "USERNAME" : "user",
      "PASSWORD" : "password",
    },
    "CONTAINER_RESOURCES" : {
      "cpu" : 1,
      "memory" : "512m",
      "ports": { 
      # OPTIONAL: these are extra ports that will be exposed to the host => v2
        "31250": 1849,
        "31251": 80
      }
    },
    "PORT" : None, # this is the app port (container port) that will be exposed to a dynamic host port
    "NGROK_AUTH_TOKEN" : None,  # put your ngrok API key here
    "NGROK_EDGE_LABEL" : None,  # if we have a already created ngrok edge, we can use it here
    "NGROK_ENABLED" : False, # this tells that the destination plugin instance will USE ngrok
    # TODO: (and observations)
    # - if NGROK_EDGE_LABEL is not None and NGROK_ENABLED is True => normal use
    # - if NGROK_EDGE_LABEL is None and NGROK_ENABLED is True => create/use dynamic url
    # - if NGROK_EDGE_LABEL is not None and NGROK_ENABLED is False => consider NGROK_ENABLED=True
    
    "NGROK_USE_API": True,  # use API or shell for ngrok tunnel creation
    "VOLUMES" : {
      "vol1" : "/host/path/vol1",
      "vol2" : "/host/path/vol2",
    },
    "ENV" : {
      "ENV1" : "value1",
      "ENV2" : "value2",
      "ENV3" : "value3",
      "ENV4" : "value4",
    },
    "DYNAMIC_ENV" : {
      "ENV5" : [
        {
          "type" : "static",
          "value" : "http://"
        },
        {
          "type" : "host_ip",
          "value" : None
        },
        {
          "type" : "static",
          "value" : ":5080/test_api_endpoint"
        }
      ],
      "ENV6" : [
        {
          "type" : "host_ip",
          "value" : "http://"
        }
      ],
    },
    "RESTART_POLICY" : "always",
    "IMAGE_PULL_POLICY" : "always",    
  },
  "pipeline_input_type"  : "void", # no other option
  "pipeline_input_uri" : None, # no other option
  "chainstore_response" : True,
}

DEEPLOY_CREATE_REQUEST_SERVICE_APP = {
  "app_alias" : "service_<service>_etc", 
  "project_id" : "DELIVERD_BY_UI = SHA256(UUID)",
  "project_name": "human-readable-project-name",
  "job_id" : "DELIVERED_BY_UI_FROM_SC",
  "plugin_signature" : "CONTAINER_APP_RUNNER",
  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
  "target_nodes" : [
    "0xai_node_1", # always single node for service apps
  ],
  "service_replica" : "0xai_service_replica_1", # this is the service replica name, it will be used to create the service app
  "node_res_req" : { 
    # this is the resource requirements for the target nodes
    # and is usable for the case when we want to deploy our service on a much 
    # powerful node than the actual container app needs
    # TODO: to be added in UI
      "cpu" : 4,
      "memory" : "16GiB"   
  },
  "app_params" : {
    "IMAGE" : "repo/image:tag", # Postgres image or MSSQL image or MySQL image
    "CR_DATA" : {
      "SERVER" : "docker.io",
      "USERNAME" : None,
      "PASSWORD" : None,
    },
    "CONTAINER_RESOURCES" : { # this are the resources that will be constrained for the container
      "cpu" : 2,
      "memory" : "2048m"
    },
    "PORT" : None, # export port 5432 to the host as well as 1433, 3306
    "NGROK_AUTH_TOKEN" : None,  # put your ngrok API key here
    "NGROK_EDGE_LABEL" : None,  # if we have a already created ngrok edge, we can use it here
    "NGROK_ENABLED" : False, # this tells that the destination plugin instance will USE ngrok
    # TODO: (and observations)
    # - if NGROK_EDGE_LABEL is not None and NGROK_ENABLED is True => normal use
    # - if NGROK_EDGE_LABEL is None and NGROK_ENABLED is True => create/use dynamic url
    # - if NGROK_EDGE_LABEL is not None and NGROK_ENABLED is False => consider NGROK_ENABLED=True
    
    "NGROK_USE_API": True,  # use API or shell for ngrok tunnel creation
    "ENV" : {
      "ENV1" : "value1",
      "ENV2" : "value2",
      "ENV3" : "value3",
      "ENV4" : "value4",
    },
    "DYNAMIC_ENV" : {
      "ENV5" : [
        {
          "type" : "static",
          "value" : "http://"
        },
        {
          "type" : "host_ip",
          "value" : None
        },
        {
          "type" : "static",
          "value" : ":5080/test_api_endpoint"
        }
      ],
      "ENV6" : [
        {
          "type" : "host_ip",
          "value" : "http://"
        }
      ],
    },
    "RESTART_POLICY" : "always",
    "IMAGE_PULL_POLICY" : "always"    
  },
  "pipeline_input_type"  : "void",
  "pipeline_input_uri" : None,
  "chainstore_response" : True,
}

DEEPLOY_CREATE_REQUES_NATIVE_APPS = {
  "app_alias" : "some_app_name",
  "project_id" : "DELIVERD_BY_UI = SHA256(UUID)",
  "project_name": "human-readable-project-name",
  "job_id" : "DELIVERED_BY_UI_FROM_SC",
  "plugin_signature" : "SOME_PLUGIN_01",
  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
  "target_nodes" : [
    "0xai_node_1",
    "0xai_node_2",
  ],
  "target_nodes_count" : 0,
  "node_res_req" : { # this is the resource requirements for the target nodes
      "cpu" : 4,
      "memory" : "16GiB"   # 16GB 16G 16Gi 16Gib 16000
  },
  "app_params" : {
    "PORT" : None,
    "NGROK_AUTH_TOKEN" : None,  # put your ngrok API key here
    "NGROK_EDGE_LABEL" : None,  # if we have a already created ngrok edge, we can use it here
    "NGROK_ENABLED" : False, # this tells that the destination plugin instance will USE ngrok
    # TODO: (and observations)
    # - if NGROK_EDGE_LABEL is not None and NGROK_ENABLED is True => normal use
    # - if NGROK_EDGE_LABEL is None and NGROK_ENABLED is True => create/use dynamic url
    # - if NGROK_EDGE_LABEL is not None and NGROK_ENABLED is False => consider NGROK_ENABLED=True

    "NGROK_USE_API": True,  # use API or shell for ngrok tunnel creation

    # TODO: in v2 we need to have for each native plugin a set of default params and their values
    #       thus the below params will be pre-completed with these default key-values

    "OTHER_PARAM1" : "value1",
    "OTHER_PARAM2" : "value2",
    "OTHER_PARAM3" : "value3",
    "OTHER_PARAM4" : "value4",
    "OTHER_PARAM5" : "value5",
  },
  "pipeline_input_type"  : "void", # DCT
  "pipeline_input_uri" : None, # DCT URL
  "pipeline_params" : {
    "pipeline_input_other1" : "ExampleDatastream", # this will be added to DCT config
    "pipeline_input_other2" : "other param",       # this will be added to DCT config
  },
  "chainstore_response" : False,
}

###################################################################################################################
# Multi-plugin request format (NEW - recommended for multiple plugins)
DEEPLOY_CREATE_REQUEST_MULTI_PLUGIN = {
  # Pipeline-level configuration
  "app_alias" : "EdgeNodeApiTest",
  "project_id" : "DELIVERD_BY_UI = SHA256(UUID)",
  "project_name": "human-readable-project-name",
  "job_id" : "DELIVERED_BY_UI_FROM_SC",
  "job_app_type": "native",
  "nonce" : hex(int(time() * 1000)),

  # Node selection
  "target_nodes" : [
    "0xai_node_1",
  ],
  "target_nodes_count" : 0,  # Use this OR target_nodes
  "spare_nodes" : [],
  "job_tags": ["KYB", "REG:EU"],
  "node_res_req" : {
    "cpu" : 4,
    "memory" : "16GiB"
  },

  # Pipeline data source
  "pipeline_input_type"  : "void",  # Pipeline TYPE
  "pipeline_input_uri" : None,
  "pipeline_params": {},
  "chainstore_response" : True,

  # Plugins array (NEW FORMAT - each object is a plugin instance)
  "plugins": [
    {
      # Plugin instance 1: EDGE_NODE_API_TEST
      "plugin_signature": "EDGE_NODE_API_TEST"
    },
    {
      # Plugin instance 2: CONTAINER_APP_RUNNER
      "plugin_signature": "CONTAINER_APP_RUNNER",
      "IMAGE": "tvitalii/ratio1-drive:latest",
      "CONTAINER_RESOURCES": {
        "cpu": 2,
        "memory": "4096m",
        "ports": {}
      },
      "CR": "docker.io",
      "ENV": {
        "INSTANCE_NAME": "R1TEST_INSTANCE"
      },
      "DYNAMIC_ENV": {
        "RATIO1_AGENT_ENDPOINT": [
          {"type": "static", "value": "http://"},
          {"type": "host_ip", "value": ""},
          {"type": "static", "value": ":15033/query"}
        ]
      },
      "VOLUMES": {
        "ks_data": "/keysoft/storage"
      },
      "PORT": None,
      "RESTART_POLICY": "always",
      "IMAGE_PULL_POLICY": "always",
      "TUNNEL_ENGINE_ENABLED": False
    }
  ]
}

###################################################################################################################
DEEPLOY_SCALE_UP_JOB_WORKERS_REQUEST = {
  "job_id" : 1, # The job ID to extend the workers for
  "app_id" : "app_id_returned_by_get_apps_or_create_pipeline", # interchange app_id with job_id
  "target_nodes" : [
    "0xai_target_node_1",
    "0xai_target_node_2",
  ],
  "target_nodes_count" : 0,
  "node_res_req" : {
    "cpu" : 4,
    "memory" : "16GiB"
  },
  "chainstore_response" : True,
  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
}
###################################################################################################################


DEEPLOY_GET_APPS_REQUEST = {
  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
}

DEEPLOY_DELETE_REQUEST = {
  "app_id" : "target_app_name_id_returned_by_get_apps_or_create_pipeline",
  "target_nodes" : [
    "0xai_target_node_1",
    "0xai_target_node_2",
  ],
  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
}  

DEEPLOY_INSTANCE_COMMAND_REQUEST = {
  "app_id" : "target_app_name_id_returned_by_get_apps_or_create_pipeline",
  "target_nodes" : [
    "0xai_target_node_1",
    "0xai_target_node_2",
  ],
  
  "plugin_signature" : "SOME_PLUGIN_01",
  "instance_id" : "SOME_PLUGIN_01_INSTANCE_ID",
  "instance_command" : "RESTART",

  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
}  

DEEPLOY_APP_COMMAND_REQUEST = {
  "app_id" : "target_app_name_id_returned_by_get_apps_or_create_pipeline",
  "plugin_singature" : "CONTAINER_APP_RUNNER", # optional plugin signature

  "command": "RESTART",

  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
}  

DEEPLOY_GET_ORACLE_JOB_DETAILS_REQUEST = {
  "job_id" : 1, # The job ID to retrieve details for
  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
}

DEEPLOY_GET_R1FS_JOB_PIPELINE_REQUEST = {
  "job_id" : 1, # The job ID to retrieve the pipeline payload for
  "nonce" : hex(int(time() * 1000)), # recoverable via int(nonce, 16)
}
