services:
  ratio1_01:
    image: ratio1/edge_node:mainnet
    container_name: r1node1
    privileged: true
    restart: always
    volumes:
      - r1vol1:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  ratio1_02:
    image: ratio1/edge_node:mainnet
    privileged: true
    container_name: r1node2
    privileged: true
    restart: always
    volumes:
      - r1vol2:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  ratio1_03:
    image: ratio1/edge_node:mainnet
    container_name: r1node3
    privileged: true
    restart: always
    volumes:
      - r1vol3:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  ratio1_04:
    image: ratio1/edge_node:mainnet
    privileged: true
    container_name: r1node4
    restart: always
    volumes:
      - r1vol4:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  ratio1_05:
    image: ratio1/edge_node:mainnet
    privileged: true
    container_name: r1node5
    restart: always
    volumes:
      - r1vol5:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  ratio1_06:
    image: ratio1/edge_node:mainnet
    privileged: true
    container_name: r1node6
    restart: always
    volumes:
      - r1vol6:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"

  ratio1_07:
    image: ratio1/edge_node:mainnet
    privileged: true
    container_name: r1node7
    restart: always
    volumes:
      - r1vol7:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  ratio1_08:
    image: ratio1/edge_node:mainnet
    privileged: true
    container_name: r1node8
    restart: always
    volumes:
      - r1vol8:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"   


  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60 # Check every 1 minute
      - WATCHTOWER_CHECK_NEW_IMAGES=true      
      - WATCHTOWER_LABEL_ENABLE=true        


volumes:
  r1vol1:
    name: r1vol1
  r1vol2:
    name: r1vol2
  r1vol3:
    name: r1vol3
  r1vol4:
    name: r1vol4
  r1vol5:
    name: r1vol5
  r1vol6:
    name: r1vol6
  r1vol7:
    name: r1vol7
  r1vol8:
    name: r1vol8