
services:
  ratio1_01:
    image: ratio1/edge_node:develop
    container_name: ratio1_01
    restart: always
    privileged: true
    environment:
      EE_ID: ${EE_ID_01?You must set the EE_ID_01 environment variable}
    env_file: .env
    volumes:
      - ratio1_01:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  ratio1_02:
    image: ratio1/edge_node:develop
    container_name: ratio1_02
    restart: always
    privileged: true
    environment:
      EE_ID: ${EE_ID_02?You must set the EE_ID_02 environment variable}
    env_file: .env
    volumes:
      - ratio1_02:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  ratio1_03:
    image: ratio1/edge_node:develop
    container_name: ratio1_03
    restart: always
    privileged: true
    environment:
      EE_ID: ${EE_ID_03?You must set the EE_ID_03 environment variable3}
    env_file: .env
    volumes:
      - ratio1_03:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          


  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60 # Check every 1 minute
      - WATCHTOWER_CHECK_NEW_IMAGES=true      
      - WATCHTOWER_LABEL_ENABLE=true        

volumes:
  ratio1_01:
    name: ratio1_01
  ratio1_02:
    name: ratio1_02
  ratio1_03:
    name: ratio1_03
