"""Fill `cve_cvss_vectors.py` with the NVD CVSS v3.x base vector of every catalog CVE.

Run by hand, with network, whenever the CVE catalog gains entries:

  PYTHONPATH=. python -m extensions.business.cybersec.red_mesh.tools.fill_cve_vectors [--out PATH] [--refresh]

Rows already in the table are kept unless `--refresh` is given, so a rerun
only fetches what is new. NVD allows 5 requests per 30 s without a key; set
`NVD_API_KEY` to go faster (50 per 30 s). The NVD's own ("Primary") metric
wins over a CNA's ("Secondary"); v3.1 over v3.0. CVEs whose record has no
v3.x metric (v2 only) are listed in `CVE_WITHOUT_V3`, not guessed (RM-087).
"""

import argparse
import datetime
import json
import os
import pathlib
import sys
import time
import urllib.request

from extensions.business.cybersec.red_mesh.cve_db import CVE_DATABASE
from extensions.business.cybersec.red_mesh.references.dynamic import NVD_CVSS_URL

_MODULE = pathlib.Path(__file__).resolve().parent.parent / "cve_cvss_vectors.py"


def nvd_v3_vector(record):
  """The v3.x base vector of one NVD 2.0 `cve` record, "" when it has none."""
  metrics = record.get("metrics") or {}
  for key in ("cvssMetricV31", "cvssMetricV30"):
    rows = metrics.get(key) or []
    rows = sorted(rows, key=lambda r: r.get("type") != "Primary")
    for row in rows:
      vector = (row.get("cvssData") or {}).get("vectorString", "")
      if vector:
        return vector
  return ""


def fetch(cve_id, api_key):
  request = urllib.request.Request(f"{NVD_CVSS_URL}?cveId={cve_id}")
  if api_key:
    request.add_header("apiKey", api_key)
  with urllib.request.urlopen(request, timeout=30) as response:
    data = json.load(response)
  vulns = data.get("vulnerabilities") or []
  if not vulns:
    raise LookupError(f"{cve_id}: not in NVD")
  return nvd_v3_vector(vulns[0].get("cve") or {})


def render(vectors, without_v3, fetched_at):
  lines = [
    '"""NVD CVSS v3.x base vector per catalog CVE (RM-087).',
    "",
    "Generated by `tools/fill_cve_vectors.py`; do not edit by hand. Rerun the",
    "tool when the catalog gains a CVE (`test_cve_cvss_vectors.py` fails until then).",
    '"""',
    "",
    f'CVE_CVSS_SOURCE = {{"nvd_api": "2.0", "fetched_at": "{fetched_at}"}}',
    "",
    "CVE_CVSS_VECTORS = {",
    *(f'  "{cve}": "{vectors[cve]}",' for cve in sorted(vectors)),
    "}",
    "",
    "# NVD records with v2 metrics only: no v3.x vector exists to attach.",
    "CVE_WITHOUT_V3 = frozenset({",
    *(f'  "{cve}",' for cve in sorted(without_v3)),
    "})",
    "",
  ]
  return "\n".join(lines)


def main(argv=None):
  parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
  parser.add_argument("--out", type=pathlib.Path, default=_MODULE)
  parser.add_argument("--refresh", action="store_true", help="refetch rows already present")
  args = parser.parse_args(argv)

  vectors, without_v3 = {}, set()
  if args.out.exists() and not args.refresh:
    namespace = {}
    exec(args.out.read_text(), namespace)
    vectors = dict(namespace.get("CVE_CVSS_VECTORS", {}))
    without_v3 = set(namespace.get("CVE_WITHOUT_V3", ()))

  api_key = os.environ.get("NVD_API_KEY", "")
  delay = 0.7 if api_key else 6.5
  wanted = sorted({entry.cve_id for entry in CVE_DATABASE} - set(vectors) - without_v3)
  failed = []
  for i, cve_id in enumerate(wanted, 1):
    try:
      vector = fetch(cve_id, api_key)
    except Exception as exc:  # network, 403 rate limit, missing record: report, keep going
      failed.append(f"{cve_id}: {exc}")
      vector = None
    if vector:
      vectors[cve_id] = vector
    elif vector == "":
      without_v3.add(cve_id)
    print(f"[{i}/{len(wanted)}] {cve_id} {vector if vector is not None else 'FAILED'}", flush=True)
    time.sleep(delay)

  fetched_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
  args.out.write_text(render(vectors, without_v3, fetched_at))
  print(f"{len(vectors)} vectors, {len(without_v3)} without v3, {len(failed)} failed -> {args.out}")
  for line in failed:
    print("  FAILED", line)
  return 1 if failed else 0


if __name__ == "__main__":
  sys.exit(main())
